camel:
  springboot:
    main-run-controller: true

case:
  input:
    from: file:///home/carlos/projects/case-iso8583/store/src/test/resources?autoCreate=true&delay=10000&delete=false
  rabbitmq:
    addresses: localhost:5672
    username: guest
    password: guest
    #ssl-protocol: TLS